server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/wts?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: skanushka
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
